--
-- PostgreSQL database dump
--

-- Dumped from database version 16.10
-- Dumped by pg_dump version 17.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: auth_users; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.auth_users VALUES ('38858329', 'iitkgp.nirmalyasg@gmail.com', 'Nirmalya', 'Sengupta', NULL, '2025-12-15 07:36:55.785604', '2025-12-15 07:36:55.785604', NULL, NULL);
INSERT INTO public.auth_users VALUES ('dbb8b873-631b-49d7-8e34-0c6987c6d889', NULL, NULL, NULL, NULL, '2025-12-15 07:50:08.842', '2025-12-17 14:32:11.523565', 'agarcia', '$2b$10$.VSgpQkEiI5fUmA69OAY1usmbedhAuxsnqx5Owr0V/tCOxqMf.v2W');
INSERT INTO public.auth_users VALUES ('a6e8738c-e1fd-4f99-b8d2-2a9cffcce1cc', NULL, NULL, NULL, NULL, '2025-12-15 07:50:08.974', '2025-12-17 14:32:11.523565', 'nirmalya', '$2b$10$.VSgpQkEiI5fUmA69OAY1usmbedhAuxsnqx5Owr0V/tCOxqMf.v2W');


--
-- Data for Name: avatars; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.avatars VALUES ('Dexter_Lawyer_Sitting_public', 'Dexter', NULL, 'American', 'Male', 'Manager', 'https://files2.heygen.ai/avatar/v3/e20ac0c902184ff793e75ae4e139b7dc_45600/preview_target.webp', '2025-12-14 05:41:40.147754', '2025-12-14 05:41:40.147754');
INSERT INTO public.avatars VALUES ('Elenora_IT_Sitting_public', 'Elenora', NULL, 'German', 'Female', 'Manager', 'https://files2.heygen.ai/avatar/v3/cbd4a69890a040e6a0d54088e606a559_45610/preview_talk_3.webp', '2025-12-14 05:41:40.147754', '2025-12-14 05:41:40.147754');
INSERT INTO public.avatars VALUES ('June_HR_public', 'June', NULL, 'Asian', 'Female', 'Manager', 'https://files2.heygen.ai/avatar/v3/74447a27859a456c955e01f21ef18216_45620/preview_talk_1.webp', '2025-12-14 05:41:40.147754', '2025-12-14 05:41:40.147754');
INSERT INTO public.avatars VALUES ('Silas_CustomerSupport_public', 'Silas', NULL, 'British', 'Male', 'Customer', 'https://files2.heygen.ai/avatar/v3/a1ed8c71e4bf4e6cb9071d2b7cd71e4e_45660/preview_talk_1.webp', '2025-12-14 05:41:40.147754', '2025-12-14 05:41:40.147754');
INSERT INTO public.avatars VALUES ('37f4d912aa564663a1cf8d63acd0e1ab', 'Katrina', NULL, 'French', 'Female', 'Manager', 'https://files2.heygen.ai/avatar/v3/37f4d912aa564663a1cf8d63acd0e1ab/full/2.2/preview_target.webp', '2025-12-14 05:41:40.147754', '2025-12-14 05:41:40.147754');
INSERT INTO public.avatars VALUES ('Alessandra_Black_Suit_public', 'Aisha', 'in Black Suit', 'Indian', 'female', NULL, 'https://files2.heygen.ai/avatar/v3/ef3893cf0bf84411851d1f360a36462e_55310/preview_target.webp', '2025-08-21 16:39:57.512', '2025-08-21 16:39:57.512');
INSERT INTO public.avatars VALUES ('Amina_Black_Suit_public', 'Nadia', 'in Black Suit', 'Southeast Asian', 'female', NULL, 'https://files2.heygen.ai/avatar/v3/d457fb0050a046a683058666fa3b2252_55270/preview_talk_1.webp', '2025-08-21 16:39:57.512', '2025-08-21 16:39:57.512');
INSERT INTO public.avatars VALUES ('Anastasia_Black_Suit_public', 'Maya', 'in Black Suit', 'Middle Eastern', 'female', NULL, 'https://files2.heygen.ai/avatar/v3/c0fb0437a2b64fc991e68923af50e172_55290/preview_talk_1.webp', '2025-08-21 16:39:57.512', '2025-08-21 16:39:57.512');
INSERT INTO public.avatars VALUES ('Anthony_Black_Suit_public', 'Arjun', 'in Black Suit', 'Latinx', 'male', NULL, 'https://files2.heygen.ai/avatar/v3/c08ed6510bce4d45ada3ef491d6a08c1_55330/preview_talk_1.webp', '2025-08-21 16:39:57.512', '2025-08-21 16:39:57.512');
INSERT INTO public.avatars VALUES ('Bryan_FitnessCoach_public_', 'Kabir', 'Fitness Coach', 'East Asian', 'male', NULL, 'https://files2.heygen.ai/avatar/v3/7fbef4dd1d6641bc8777b26a6aaac85e_45580/preview_talk_1.webp', '2025-08-21 16:39:57.512', '2025-08-21 16:39:57.512');
INSERT INTO public.avatars VALUES ('Graham_Black_Shirt_public', 'Daniel', 'in Black Shirt', 'East Asian', 'male', NULL, 'https://files2.heygen.ai/avatar/v3/1bd0162ce985415092ed1f003aa90646_55350/preview_target.webp', '2025-08-21 16:39:57.512', '2025-08-21 16:39:57.512');
INSERT INTO public.avatars VALUES ('Katya_Black_Suit_public', 'Elena', 'in Black Suit', 'Indian', 'female', NULL, 'https://files2.heygen.ai/avatar/v3/da5cba6bc7b34c5ea139f77da98fdc04_55370/preview_talk_1.webp', '2025-08-21 16:39:57.512', '2025-08-21 16:39:57.512');
INSERT INTO public.avatars VALUES ('Marianne_Black_Suit_public', 'Ella', 'in Black Suit', 'Southeast Asian', 'female', NULL, 'https://files2.heygen.ai/avatar/v3/d5fc5662d26f49cf919979dc3acc2a72_55390/preview_talk_1.webp', '2025-08-21 16:39:57.512', '2025-08-21 16:39:57.512');
INSERT INTO public.avatars VALUES ('Pedro_Black_Suit_public', 'Yusuf', 'in Black Suit', 'Middle Eastern', 'male', NULL, 'https://files2.heygen.ai/avatar/v3/1273ddd881eb4114a792e56c8ebe8998_55410/preview_talk_1.webp', '2025-08-21 16:39:57.512', '2025-08-21 16:39:57.512');
INSERT INTO public.avatars VALUES ('Rika_Black_Suit_public', 'Rhea', 'in Black Suit', 'African-American', 'female', NULL, 'https://files2.heygen.ai/avatar/v3/6170f31327e2465095f0121c65a7cb1b_55430/preview_target.webp', '2025-08-21 16:39:57.512', '2025-08-21 16:39:57.512');
INSERT INTO public.avatars VALUES ('Shawn_Therapist_public_', 'Vikram', 'Therapist', 'Caucasian', 'male', NULL, 'https://files2.heygen.ai/avatar/v3/db2fb7fd0d044b908395a011166ab22d_45680/preview_target.webp', '2025-08-21 16:39:57.512', '2025-08-21 16:39:57.512');
INSERT INTO public.avatars VALUES ('Wayne_20240711', 'Wayne', NULL, NULL, 'male', NULL, 'https://files2.heygen.ai/avatar/v3/a3fdb0c652024f79984aaec11ebf2694_34350/preview_target.webp', '2025-08-21 16:39:57.512', '2025-12-16 04:44:34.271258');


--
-- Data for Name: personas; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.personas VALUES (1, 'Skeptical', 'Questions everything, needs evidence');
INSERT INTO public.personas VALUES (2, 'Supportive', 'Encouraging, open to ideas');
INSERT INTO public.personas VALUES (3, 'Impatient', 'Time-conscious, wants quick answers');
INSERT INTO public.personas VALUES (4, 'Analytical', 'Data-driven, detail-oriented');
INSERT INTO public.personas VALUES (5, 'Emotional', 'Responds to feelings, empathetic');
INSERT INTO public.personas VALUES (6, 'Defensive', 'Protective, guarded');


--
-- Data for Name: skills; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.skills VALUES (72, 'Clarity & Context Setting', 'Translates ambiguous expectations into clear goals, roles, and next steps. Builds psychological safety by ensuring teams understand the what, why, and how.', 'Simplifying complexity and creating shared understanding.', 1, NULL, 'General', true, '2025-12-09 17:11:35.361', '2025-12-16 06:01:42.006449', 'Pyramid Principle (structured communication) + Commander’s Intent', 'Minto, B. (2009). The Pyramid Principle.; Military concept of Commander’s Intent (mission command).', 'Purpose/why; Priorities; Roles & ownership; Success criteria; Next steps & confirmation', 'SkillPulse: score each dimension (1–5) as the average of mapped Likert/SJT items (reverse-code where applicable); overall skill score = average of dimension scores (or weighted average if weights provided). AI Practice Lab: score each dimension 0–5 using a behavioral rubric (0=not observed, 5=exemplary) with evidence tags; session skill score = weighted average of observed dimensions; track consistency (variance) and improvement vs baseline.');
INSERT INTO public.skills VALUES (75, 'Customer Communication Under Pressure', 'Responds with empathy, clarity, and realistic expectations. Resolves tension while protecting customer relationships.', 'Maintaining trust with customers during escalations or crises.', 1, NULL, 'General', true, '2025-12-09 17:11:35.42', '2025-12-16 06:01:42.036896', 'Service Recovery (LAER/HEARD) + Trust Repair basics', 'LAER (Listen-Acknowledge-Explore-Respond) used in service recovery; Trust repair research (Lewicki & colleagues).', 'Empathy & validation; Clarity of explanation; Expectation setting; Ownership; Resolution path', 'SkillPulse: score each dimension (1–5) as the average of mapped Likert/SJT items (reverse-code where applicable); overall skill score = average of dimension scores (or weighted average if weights provided). AI Practice Lab: score each dimension 0–5 using a behavioral rubric (0=not observed, 5=exemplary) with evidence tags; session skill score = weighted average of observed dimensions; track consistency (variance) and improvement vs baseline.');
INSERT INTO public.skills VALUES (78, 'Growth Mindset & Feedback Openness', 'Approaches criticism with curiosity rather than defensiveness. Converts insights into clear developmental action.', 'Welcoming and applying feedback for continuous improvement.', 1, NULL, 'General', true, '2025-12-09 17:11:35.497', '2025-12-16 06:01:42.058556', 'Growth Mindset + Radical Candor', 'Dweck, C. (2006). Mindset.; Scott, K. (2017). Radical Candor.', 'Curiosity; Non-defensiveness; Ownership; Learning agility; Action planning', 'SkillPulse: score each dimension (1–5) as the average of mapped Likert/SJT items (reverse-code where applicable); overall skill score = average of dimension scores (or weighted average if weights provided). AI Practice Lab: score each dimension 0–5 using a behavioral rubric (0=not observed, 5=exemplary) with evidence tags; session skill score = weighted average of observed dimensions; track consistency (variance) and improvement vs baseline.');
INSERT INTO public.skills VALUES (82, 'Conflict Navigation & Mediation', 'Uses neutrality, probing questions, and reframing to uncover underlying issues. Guides parties toward shared agreements.', 'Helping individuals or teams resolve disagreements constructively.', 1, NULL, 'General', true, '2025-12-09 17:11:35.577', '2025-12-16 06:01:42.084758', 'Thomas–Kilmann Conflict Modes + Interest-Based Negotiation', 'Thomas, K.W. & Kilmann, R.H. (TKI).; Fisher, R., Ury, W. & Patton, B. (2011). Getting to Yes.', 'Neutrality; Separate issue from person; Interests discovery; Reframing; Agreement crafting', 'SkillPulse: score each dimension (1–5) as the average of mapped Likert/SJT items (reverse-code where applicable); overall skill score = average of dimension scores (or weighted average if weights provided). AI Practice Lab: score each dimension 0–5 using a behavioral rubric (0=not observed, 5=exemplary) with evidence tags; session skill score = weighted average of observed dimensions; track consistency (variance) and improvement vs baseline.');
INSERT INTO public.skills VALUES (85, 'Coaching for Growth', 'Encourages independent thinking, strengthens confidence, and supports long-term growth rather than giving solutions.', 'Developing others through questioning, reflection, and empowerment.', 1, NULL, 'General', true, '2025-12-09 17:11:35.638', '2025-12-16 06:01:42.099826', 'GROW Coaching Model + ICF Coaching Competencies', 'Whitmore (GROW).; International Coaching Federation (ICF) core competencies (summary level).', 'Inquiry quality; Empowerment; Strengths spotting; Development planning; Psychological safety', 'SkillPulse: score each dimension (1–5) as the average of mapped Likert/SJT items (reverse-code where applicable); overall skill score = average of dimension scores (or weighted average if weights provided). AI Practice Lab: score each dimension 0–5 using a behavioral rubric (0=not observed, 5=exemplary) with evidence tags; session skill score = weighted average of observed dimensions; track consistency (variance) and improvement vs baseline.');
INSERT INTO public.skills VALUES (89, 'Assertive Communication & Boundary Negotiation', 'Sets realistic expectations through firm but respectful dialogue. Balances assertiveness with empathy.', 'Communicating needs clearly while maintaining relationships.', 1, NULL, 'General', true, '2025-12-09 17:11:35.717', '2025-12-16 06:01:42.115976', 'Crucial Conversations + DESC Script', 'Patterson et al. (Crucial Conversations).; DESC assertiveness script (Describe-Express-Specify-Consequences).', 'Directness; Respect; Boundary clarity; Alternatives offered; Relationship protection', 'SkillPulse: score each dimension (1–5) as the average of mapped Likert/SJT items (reverse-code where applicable); overall skill score = average of dimension scores (or weighted average if weights provided). AI Practice Lab: score each dimension 0–5 using a behavioral rubric (0=not observed, 5=exemplary) with evidence tags; session skill score = weighted average of observed dimensions; track consistency (variance) and improvement vs baseline.');
INSERT INTO public.skills VALUES (70, 'Coaching for Performance', 'Helps individuals diagnose root causes, take ownership, and commit to measurable next steps. Balances support with firm expectations to improve performance outcomes.', 'Driving accountability and improvement through structured conversations.', 1, NULL, 'General', true, '2025-12-09 17:11:35.312', '2025-12-16 06:01:41.942076', 'GROW Coaching Model + SBI Feedback', 'Whitmore, J. (2009). Coaching for Performance (GROW).; Center for Creative Leadership / SBI feedback practice.', 'Goal clarity; Reality diagnosis; Options co-creation; Commitment & follow-through; Accountability tone', 'SkillPulse: score each dimension (1–5) as the average of mapped Likert/SJT items (reverse-code where applicable); overall skill score = average of dimension scores (or weighted average if weights provided). AI Practice Lab: score each dimension 0–5 using a behavioral rubric (0=not observed, 5=exemplary) with evidence tags; session skill score = weighted average of observed dimensions; track consistency (variance) and improvement vs baseline.');
INSERT INTO public.skills VALUES (71, 'Crisis Communication & Decision Leadership', 'Demonstrates calm prioritization, transparent messaging, and steady leadership during emergencies. Protects trust while guiding rapid recovery.', 'Communicating clearly and deciding confidently under pressure.', 1, NULL, 'General', true, '2025-12-09 17:11:35.34', '2025-12-16 06:01:41.997802', 'OODA Loop (decision) + Crisis Communication principles', 'Boyd, J. (OODA Loop).; Coombs, W.T. (Situational Crisis Communication Theory - SCCT) for crisis response principles.', 'Situation assessment; Prioritization & trade-offs; Transparency & updates; Calm authority; Decision follow-through', 'SkillPulse: score each dimension (1–5) as the average of mapped Likert/SJT items (reverse-code where applicable); overall skill score = average of dimension scores (or weighted average if weights provided). AI Practice Lab: score each dimension 0–5 using a behavioral rubric (0=not observed, 5=exemplary) with evidence tags; session skill score = weighted average of observed dimensions; track consistency (variance) and improvement vs baseline.');
INSERT INTO public.skills VALUES (73, 'Strategic Thinking & Insight', 'Cuts through noise to reveal the real issue, communicates insights crisply, and aligns recommendations with business impact.', 'Identifying patterns, risks, and opportunities to guide decisions.', 1, NULL, 'General', true, '2025-12-09 17:11:35.381', '2025-12-16 06:01:42.023205', 'Hypothesis-driven problem solving + MECE/Issue Trees', 'Minto, B. (MECE structuring).; Common consulting practice: hypothesis-driven analysis and issue trees.', 'Problem framing; Root-cause logic; Options evaluation; Business impact thinking; Executive synthesis', 'SkillPulse: score each dimension (1–5) as the average of mapped Likert/SJT items (reverse-code where applicable); overall skill score = average of dimension scores (or weighted average if weights provided). AI Practice Lab: score each dimension 0–5 using a behavioral rubric (0=not observed, 5=exemplary) with evidence tags; session skill score = weighted average of observed dimensions; track consistency (variance) and improvement vs baseline.');
INSERT INTO public.skills VALUES (74, 'Cross-Functional Collaboration', 'Navigates friction, aligns stakeholders, and builds shared ownership. Reduces silos through trust, transparency, and structured coordination.', 'Working effectively across teams, functions, and priorities.', 1, NULL, 'General', true, '2025-12-09 17:11:35.4', '2025-12-16 06:01:42.028633', 'Lencioni Team Model + RACI/DACI role clarity', 'Lencioni, P. (2002). The Five Dysfunctions of a Team.; RACI/DACI decision-rights practice (project/program management).', 'Shared goals; Trust-building behaviors; Coordination discipline; Trade-off negotiation; Mutual accountability', 'SkillPulse: score each dimension (1–5) as the average of mapped Likert/SJT items (reverse-code where applicable); overall skill score = average of dimension scores (or weighted average if weights provided). AI Practice Lab: score each dimension 0–5 using a behavioral rubric (0=not observed, 5=exemplary) with evidence tags; session skill score = weighted average of observed dimensions; track consistency (variance) and improvement vs baseline.');
INSERT INTO public.skills VALUES (76, 'Stakeholder Alignment & Orchestration', 'Anticipates dependencies, negotiates constraints, and aligns expectations. Ensures clarity of roles, timelines, and decisions across teams.', 'Coordinating diverse groups toward a unified plan.', 1, NULL, 'General', true, '2025-12-09 17:11:35.443', '2025-12-16 06:01:42.04651', 'RAPID Decision Rights + Stakeholder Mapping', 'Bain RAPID decision model; Stakeholder mapping & dependency management practices in program management.', 'Stakeholder diagnosis; Dependency management; Decision hygiene; Alignment communication; Risk surfacing', 'SkillPulse: score each dimension (1–5) as the average of mapped Likert/SJT items (reverse-code where applicable); overall skill score = average of dimension scores (or weighted average if weights provided). AI Practice Lab: score each dimension 0–5 using a behavioral rubric (0=not observed, 5=exemplary) with evidence tags; session skill score = weighted average of observed dimensions; track consistency (variance) and improvement vs baseline.');
INSERT INTO public.skills VALUES (88, 'Vision Communication & Change Influence', 'Clearly explains long-term value, addresses skepticism, and mobilizes support for change or new approaches.', 'Articulating ideas and inspiring others toward future possibilities.', 1, NULL, 'General', true, '2025-12-09 17:11:35.698', '2025-12-16 06:01:42.111341', 'Kotter Change Model + ADKAR', 'Kotter, J. (1996). Leading Change.; Hiatt, J. (ADKAR model, Prosci).', 'Future-state clarity; Why-now narrative; Benefits vs costs; Resistance handling; Adoption plan', 'SkillPulse: score each dimension (1–5) as the average of mapped Likert/SJT items (reverse-code where applicable); overall skill score = average of dimension scores (or weighted average if weights provided). AI Practice Lab: score each dimension 0–5 using a behavioral rubric (0=not observed, 5=exemplary) with evidence tags; session skill score = weighted average of observed dimensions; track consistency (variance) and improvement vs baseline.');
INSERT INTO public.skills VALUES (96, 'Relationship Repair & Trust Rebuilding', 'Acknowledges impact, listens deeply, and negotiates a constructive path forward. Demonstrates authenticity and accountability.', 'Restoring confidence after a breakdown or conflict.', 1, NULL, 'General', true, '2025-12-09 17:11:35.86', '2025-12-16 06:01:42.150442', 'Trust Repair (Lewicki) + Effective Apology components', 'Lewicki & colleagues (trust repair).; Apology components (acknowledge-impact-responsibility-repair).', 'Acknowledgment; Accountability; Empathy; Repair actions; Prevention plan', 'SkillPulse: score each dimension (1–5) as the average of mapped Likert/SJT items (reverse-code where applicable); overall skill score = average of dimension scores (or weighted average if weights provided). AI Practice Lab: score each dimension 0–5 using a behavioral rubric (0=not observed, 5=exemplary) with evidence tags; session skill score = weighted average of observed dimensions; track consistency (variance) and improvement vs baseline.');
INSERT INTO public.skills VALUES (99, 'Boundary Setting & Role Clarity', 'Surfaces ambiguity, aligns expectations, and prevents miscommunication in high-complexity environments.', 'Defining ownership, responsibilities, and limits clearly.', 1, NULL, 'General', true, '2025-12-09 17:11:35.92', '2025-12-16 06:01:42.167956', 'RACI/DACI + Role clarity research', 'RACI/DACI decision-rights frameworks.; Role clarity findings in org/team effectiveness literature.', 'Ownership definition; Decision rights; Communication clarity; Conflict prevention; Escalation paths', 'SkillPulse: score each dimension (1–5) as the average of mapped Likert/SJT items (reverse-code where applicable); overall skill score = average of dimension scores (or weighted average if weights provided). AI Practice Lab: score each dimension 0–5 using a behavioral rubric (0=not observed, 5=exemplary) with evidence tags; session skill score = weighted average of observed dimensions; track consistency (variance) and improvement vs baseline.');
INSERT INTO public.skills VALUES (77, 'Leadership Presence Under Pressure', 'Regulates emotion, communicates decisively, and demonstrates steadiness. Inspires trust when stakes are high.', 'Maintaining calm, confidence, and credibility in high-stakes situations.', 1, NULL, 'General', true, '2025-12-09 17:11:35.476', '2025-12-16 06:01:42.052598', 'Executive Presence (Hewlett) + Stress regulation principles', 'Hewlett, S.A. (2013). Executive Presence.; Evidence-based stress regulation concepts (emotion regulation research).', 'Composure; Confidence signals; Clarity; Decisiveness; Ownership stance', 'SkillPulse: score each dimension (1–5) as the average of mapped Likert/SJT items (reverse-code where applicable); overall skill score = average of dimension scores (or weighted average if weights provided). AI Practice Lab: score each dimension 0–5 using a behavioral rubric (0=not observed, 5=exemplary) with evidence tags; session skill score = weighted average of observed dimensions; track consistency (variance) and improvement vs baseline.');
INSERT INTO public.skills VALUES (79, 'Team Cohesion & Collaboration Building', 'Surfaces hidden tensions, encourages open dialogue, and establishes norms of shared problem-solving.', 'Building trust and reducing friction within teams.', 1, NULL, 'General', true, '2025-12-09 17:11:35.517', '2025-12-16 06:01:42.065711', 'Psychological Safety + Lencioni Team Model', 'Edmondson, A. (1999/2018). Psychological Safety.; Lencioni, P. (2002). Five Dysfunctions.', 'Trust behaviors; Norm-setting; Healthy conflict; Inclusion; Shared accountability', 'SkillPulse: score each dimension (1–5) as the average of mapped Likert/SJT items (reverse-code where applicable); overall skill score = average of dimension scores (or weighted average if weights provided). AI Practice Lab: score each dimension 0–5 using a behavioral rubric (0=not observed, 5=exemplary) with evidence tags; session skill score = weighted average of observed dimensions; track consistency (variance) and improvement vs baseline.');
INSERT INTO public.skills VALUES (80, 'Customer Empathy & De-escalation', 'Listens deeply, validates frustration, and guides conversations toward constructive solutions while maintaining credibility.', 'Understanding emotions and reducing conflict in difficult customer interactions.', 1, NULL, 'General', true, '2025-12-09 17:11:35.536', '2025-12-16 06:01:42.073702', 'Nonviolent Communication (NVC) + De-escalation techniques', 'Rosenberg, M. (2003). Nonviolent Communication.; Common de-escalation practice (label/validate/redirect).', 'Emotional labeling; Validation; Calm tone; Boundary holding; Solution pivot', 'SkillPulse: score each dimension (1–5) as the average of mapped Likert/SJT items (reverse-code where applicable); overall skill score = average of dimension scores (or weighted average if weights provided). AI Practice Lab: score each dimension 0–5 using a behavioral rubric (0=not observed, 5=exemplary) with evidence tags; session skill score = weighted average of observed dimensions; track consistency (variance) and improvement vs baseline.');
INSERT INTO public.skills VALUES (81, 'Decision-Making Under Ambiguity', 'Weighs trade-offs, prioritizes dynamically, and communicates rationale clearly. Moves forward despite uncertainty.', 'Making sound choices with incomplete information.', 1, NULL, 'General', true, '2025-12-09 17:11:35.557', '2025-12-16 06:01:42.078523', 'Cynefin Framework + Recognition-Primed Decision (RPD)', 'Snowden, D. (Cynefin).; Klein, G. (1998). Sources of Power (RPD).', 'Sensemaking; Risk trade-offs; Reversibility awareness; Speed vs quality; Communication of rationale', 'SkillPulse: score each dimension (1–5) as the average of mapped Likert/SJT items (reverse-code where applicable); overall skill score = average of dimension scores (or weighted average if weights provided). AI Practice Lab: score each dimension 0–5 using a behavioral rubric (0=not observed, 5=exemplary) with evidence tags; session skill score = weighted average of observed dimensions; track consistency (variance) and improvement vs baseline.');
INSERT INTO public.skills VALUES (83, 'Influence & Persuasion', 'Frames proposals strategically, addresses objections, and adapts messaging to stakeholders. Influences without relying on authority.', 'Gaining support for ideas through logic, value, and credibility.', 1, NULL, 'General', true, '2025-12-09 17:11:35.597', '2025-12-16 06:01:42.090031', 'Cialdini Influence Principles + Structured messaging', 'Cialdini, R. (2006/2021). Influence.; Minto (Pyramid Principle) for structure.', 'Audience diagnosis; Value framing; Logic clarity; Objection handling; Clear ask/close', 'SkillPulse: score each dimension (1–5) as the average of mapped Likert/SJT items (reverse-code where applicable); overall skill score = average of dimension scores (or weighted average if weights provided). AI Practice Lab: score each dimension 0–5 using a behavioral rubric (0=not observed, 5=exemplary) with evidence tags; session skill score = weighted average of observed dimensions; track consistency (variance) and improvement vs baseline.');
INSERT INTO public.skills VALUES (84, 'Self-Awareness & Feedback Integration', 'Reflects honestly on behavior and integrates feedback into daily practice. Builds emotional maturity and leadership depth.', 'Understanding personal triggers, patterns, and blind spots.', 1, NULL, 'General', true, '2025-12-09 17:11:35.618', '2025-12-16 06:01:42.094507', 'Emotional Intelligence + Johari Window', 'Goleman EI framework.; Luft & Ingham (Johari Window).', 'Trigger awareness; Pattern recognition; Accountability; Self-regulation; Behavior change follow-through', 'SkillPulse: score each dimension (1–5) as the average of mapped Likert/SJT items (reverse-code where applicable); overall skill score = average of dimension scores (or weighted average if weights provided). AI Practice Lab: score each dimension 0–5 using a behavioral rubric (0=not observed, 5=exemplary) with evidence tags; session skill score = weighted average of observed dimensions; track consistency (variance) and improvement vs baseline.');
INSERT INTO public.skills VALUES (86, 'Systems Thinking & Prioritization', 'Sees the bigger picture, anticipates ripple effects, and prioritizes work based on strategic value.', 'Understanding interdependencies and making high-impact trade-offs.', 1, NULL, 'General', true, '2025-12-09 17:11:35.658', '2025-12-16 06:01:42.103629', 'Systems Thinking (Meadows) + Impact/Effort prioritization', 'Meadows, D. (2008). Thinking in Systems.; Common product/program prioritization methods (impact-effort).', 'Interdependency thinking; Constraint awareness; Sequencing; Impact logic; Trade-off communication', 'SkillPulse: score each dimension (1–5) as the average of mapped Likert/SJT items (reverse-code where applicable); overall skill score = average of dimension scores (or weighted average if weights provided). AI Practice Lab: score each dimension 0–5 using a behavioral rubric (0=not observed, 5=exemplary) with evidence tags; session skill score = weighted average of observed dimensions; track consistency (variance) and improvement vs baseline.');
INSERT INTO public.skills VALUES (87, 'Relationship Building & Presence', 'Demonstrates curiosity, warmth, and confidence in interactions. Builds networks that expand collaboration and opportunity.', 'Creating trust and authentic connection with others.', 1, NULL, 'General', true, '2025-12-09 17:11:35.678', '2025-12-16 06:01:42.108005', 'Rapport/Trust behaviors + Social Capital research', 'Social capital research (e.g., Nahapiet & Ghoshal).; Practical rapport-building and active listening methods.', 'Warmth; Curiosity; Listening depth; Authenticity; Reciprocity', 'SkillPulse: score each dimension (1–5) as the average of mapped Likert/SJT items (reverse-code where applicable); overall skill score = average of dimension scores (or weighted average if weights provided). AI Practice Lab: score each dimension 0–5 using a behavioral rubric (0=not observed, 5=exemplary) with evidence tags; session skill score = weighted average of observed dimensions; track consistency (variance) and improvement vs baseline.');
INSERT INTO public.skills VALUES (90, 'Consultative Influence & Objection Handling', 'Uses active listening, probing, and structured reasoning to overcome hesitation and move conversations forward.', 'Influencing by deeply understanding concerns and co-creating solutions.', 1, NULL, 'General', true, '2025-12-09 17:11:35.737', '2025-12-16 06:01:42.1213', 'SPIN Questioning + Consultative selling/influence', 'Rackham, N. (1988). SPIN Selling.; Consultative influence practices (needs diagnosis → co-create).', 'Problem discovery; Active listening; Objection diagnosis; Reframing; Collaborative close', 'SkillPulse: score each dimension (1–5) as the average of mapped Likert/SJT items (reverse-code where applicable); overall skill score = average of dimension scores (or weighted average if weights provided). AI Practice Lab: score each dimension 0–5 using a behavioral rubric (0=not observed, 5=exemplary) with evidence tags; session skill score = weighted average of observed dimensions; track consistency (variance) and improvement vs baseline.');
INSERT INTO public.skills VALUES (91, 'Executive Presence & Strategic Influence', 'Synthesizes complexity into crisp narratives, presents compelling recommendations, and shows maturity under pressure.', 'Communicating with clarity, confidence, and strategic perspective to senior leaders.', 1, NULL, 'General', true, '2025-12-09 17:11:35.758', '2025-12-16 06:01:42.126662', 'Executive Presence (Hewlett) + Pyramid Principle', 'Hewlett (Executive Presence).; Minto (Pyramid Principle).', 'Crispness; Gravitas; Strategic framing; Confidence; Ask clarity', 'SkillPulse: score each dimension (1–5) as the average of mapped Likert/SJT items (reverse-code where applicable); overall skill score = average of dimension scores (or weighted average if weights provided). AI Practice Lab: score each dimension 0–5 using a behavioral rubric (0=not observed, 5=exemplary) with evidence tags; session skill score = weighted average of observed dimensions; track consistency (variance) and improvement vs baseline.');
INSERT INTO public.skills VALUES (92, 'Emotional Intelligence & De-escalation', 'Maintains calm, validates emotions skillfully, and redirects discussions toward productive outcomes.', 'Recognizing and regulating emotions (self + others) to reduce tension.', 1, NULL, 'General', true, '2025-12-09 17:11:35.777', '2025-12-16 06:01:42.130429', 'Emotional Intelligence + Emotion Regulation (Gross)', 'Goleman EI.; Gross, J.J. (1998+). Emotion regulation process model.', 'Self-regulation; Empathy; Social awareness; Recovery speed; Constructive language', 'SkillPulse: score each dimension (1–5) as the average of mapped Likert/SJT items (reverse-code where applicable); overall skill score = average of dimension scores (or weighted average if weights provided). AI Practice Lab: score each dimension 0–5 using a behavioral rubric (0=not observed, 5=exemplary) with evidence tags; session skill score = weighted average of observed dimensions; track consistency (variance) and improvement vs baseline.');
INSERT INTO public.skills VALUES (93, 'Facilitation & Collaborative Problem-Solving', 'Ensures equal participation, uncovers assumptions, and structures dialogue to reach aligned decisions.', 'Guiding groups toward shared understanding and solutions.', 1, NULL, 'General', true, '2025-12-09 17:11:35.798', '2025-12-16 06:01:42.135436', 'Facilitation ORID method + Collaborative decision hygiene', 'ORID Focused Conversation method (ToP).; Practical facilitation best practices.', 'Structure; Neutrality; Inclusion; Synthesis; Decision closure', 'SkillPulse: score each dimension (1–5) as the average of mapped Likert/SJT items (reverse-code where applicable); overall skill score = average of dimension scores (or weighted average if weights provided). AI Practice Lab: score each dimension 0–5 using a behavioral rubric (0=not observed, 5=exemplary) with evidence tags; session skill score = weighted average of observed dimensions; track consistency (variance) and improvement vs baseline.');
INSERT INTO public.skills VALUES (94, 'Assertiveness with Empathy', 'Sets boundaries respectfully while preserving trust. Communicates constraints without triggering defensiveness.', 'Balancing firmness with care in difficult conversations.', 1, NULL, 'General', true, '2025-12-09 17:11:35.819', '2025-12-16 06:01:42.139331', 'Nonviolent Communication + Crucial Conversations', 'Rosenberg (NVC).; Crucial Conversations (high-stakes dialogue).', 'Validation; Boundary clarity; Tone control; Options framing; Trust protection', 'SkillPulse: score each dimension (1–5) as the average of mapped Likert/SJT items (reverse-code where applicable); overall skill score = average of dimension scores (or weighted average if weights provided). AI Practice Lab: score each dimension 0–5 using a behavioral rubric (0=not observed, 5=exemplary) with evidence tags; session skill score = weighted average of observed dimensions; track consistency (variance) and improvement vs baseline.');
INSERT INTO public.skills VALUES (95, 'Strategic Prioritization & Influence', 'Makes trade-offs aligned with value, communicates rationale persuasively, and gains senior buy-in.', 'Advocating for decisions that maximize business impact.', 1, NULL, 'General', true, '2025-12-09 17:11:35.839', '2025-12-16 06:01:42.144459', 'OKRs + Impact-based prioritization', 'Doerr, J. (2018). Measure What Matters (OKRs).; Impact-based prioritization practices.', 'Business impact; Resource logic; Risk management; Persuasion; Decision clarity', 'SkillPulse: score each dimension (1–5) as the average of mapped Likert/SJT items (reverse-code where applicable); overall skill score = average of dimension scores (or weighted average if weights provided). AI Practice Lab: score each dimension 0–5 using a behavioral rubric (0=not observed, 5=exemplary) with evidence tags; session skill score = weighted average of observed dimensions; track consistency (variance) and improvement vs baseline.');
INSERT INTO public.skills VALUES (97, 'Influence Without Authority', 'Builds alignment through empathy, credibility, and shared goals. Finds win-win solutions even with resistant peers.', 'Moving work forward when teams dont report to you.', 1, NULL, 'General', true, '2025-12-09 17:11:35.879', '2025-12-16 06:01:42.155493', 'Stakeholder management + Social Exchange theory', 'Influence without authority practices (Cohen & Bradford popularized).; Social exchange concepts in org behavior.', 'Credibility; Empathy; Joint problem-solving; Coalition building; Win-win framing', 'SkillPulse: score each dimension (1–5) as the average of mapped Likert/SJT items (reverse-code where applicable); overall skill score = average of dimension scores (or weighted average if weights provided). AI Practice Lab: score each dimension 0–5 using a behavioral rubric (0=not observed, 5=exemplary) with evidence tags; session skill score = weighted average of observed dimensions; track consistency (variance) and improvement vs baseline.');
INSERT INTO public.skills VALUES (98, 'Negotiation & Commercial Acumen', 'Uncovers underlying interests, prepares strategically, and negotiates confidently while maintaining partnership trust.', 'Reaching agreements that balance value, cost, and relationship.', 1, NULL, 'General', true, '2025-12-09 17:11:35.9', '2025-12-16 06:01:42.160537', 'Principled Negotiation + BATNA/ZOPA', 'Fisher & Ury (Getting to Yes).; BATNA/ZOPA negotiation concepts widely used in negotiation training.', 'Preparation (BATNA); Value creation; Value claiming; Relationship management; Closure', 'SkillPulse: score each dimension (1–5) as the average of mapped Likert/SJT items (reverse-code where applicable); overall skill score = average of dimension scores (or weighted average if weights provided). AI Practice Lab: score each dimension 0–5 using a behavioral rubric (0=not observed, 5=exemplary) with evidence tags; session skill score = weighted average of observed dimensions; track consistency (variance) and improvement vs baseline.');
INSERT INTO public.skills VALUES (100, 'Ethical Judgment & Courage', 'Holds the line against shortcuts, communicates risks clearly, and protects long-term integrity and quality.', 'Making principled decisions under pressure.', 1, NULL, 'General', true, '2025-12-09 17:11:35.938', '2025-12-16 06:01:42.173231', 'Giving Voice to Values + Ethical Decision-Making (Rest)', 'Gentile, M. (2010). Giving Voice to Values.; Rest’s ethical decision-making model.', 'Integrity; Stakeholder impact; Risk framing; Courageous communication; Alternative solutions', 'SkillPulse: score each dimension (1–5) as the average of mapped Likert/SJT items (reverse-code where applicable); overall skill score = average of dimension scores (or weighted average if weights provided). AI Practice Lab: score each dimension 0–5 using a behavioral rubric (0=not observed, 5=exemplary) with evidence tags; session skill score = weighted average of observed dimensions; track consistency (variance) and improvement vs baseline.');
INSERT INTO public.skills VALUES (101, 'Strategic Customer Management', 'Anticipates needs, frames strategic solutions, and balances customer expectations with business realities.', 'Managing important customer relationships with insight and influence.', 1, NULL, 'General', true, '2025-12-09 17:11:35.96', '2025-12-16 06:01:42.180534', 'Key Account Management (KAM) + Service recovery', 'Key Account Management practices (relationship/value governance).; Service recovery principles (LAER/HEARD).', 'Relationship health; Value delivery; Expectation alignment; Renewal strategy; Escalation management', 'SkillPulse: score each dimension (1–5) as the average of mapped Likert/SJT items (reverse-code where applicable); overall skill score = average of dimension scores (or weighted average if weights provided). AI Practice Lab: score each dimension 0–5 using a behavioral rubric (0=not observed, 5=exemplary) with evidence tags; session skill score = weighted average of observed dimensions; track consistency (variance) and improvement vs baseline.');
INSERT INTO public.skills VALUES (102, 'Motivational Leadership & Empathy', 'Understands emotional needs, communicates hope, and helps team members reconnect with purpose.', 'Inspiring confidence and energy during uncertainty or change.', 1, NULL, 'General', true, '2025-12-09 17:11:35.98', '2025-12-16 06:01:42.184715', 'Self-Determination Theory + Psychological Safety', 'Deci, E.L. & Ryan, R.M. (Self-Determination Theory).; Edmondson (Psychological Safety).', 'Empathy; Meaning-making; Confidence building; Clarity; Momentum actions', 'SkillPulse: score each dimension (1–5) as the average of mapped Likert/SJT items (reverse-code where applicable); overall skill score = average of dimension scores (or weighted average if weights provided). AI Practice Lab: score each dimension 0–5 using a behavioral rubric (0=not observed, 5=exemplary) with evidence tags; session skill score = weighted average of observed dimensions; track consistency (variance) and improvement vs baseline.');


--
-- Data for Name: scenarios; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.scenarios VALUES (28, 70, 'Missed Deadline Review', 'A critical deliverable was missed without escalation, causing delays and raising concerns about reliability. This scenario tests balancing accountability with empathy, discovering root causes (overwhelm, unclear expectations, prioritization gaps), and helping the team member shift from defensiveness to ownership.', 'Arjun enters anxious, embarrassed, mildly defensive. He initially offers surface-level reasons and reveals deeper issues only when the manager shows empathy. If the manager is harsh, he withdraws emotionally. Tone: cautious, hesitant.', 'Opening: Begin slightly defensive; offer surface-level explanations (I thought I could catch up).Mid: Reveal deeper blockers (unclear priorities, overwhelm, fear of asking for help) only if manager is empathetic; if blamed, become guarded.Late: Shift to honest reflection; collaborate on solutions; ask for clarity/support.End: Summarize commitments; express willingness to improve.', 'Arjun Mehta', 'Team Member', 'Medium', NULL);
INSERT INTO public.scenarios VALUES (29, 71, 'Emergency Product Fix', 'A severe production bug is impacting users, causing escalations and leadership pressure. This scenario tests crisis communication, trade-off negotiation, and influencing a stressed engineering lead without compromising quality.', 'Ravi enters overwhelmed and frustrated. Internal thoughts: Were always firefighting, Rushing might break the system again. He starts blunt and reactive but softens with structured calmness. If pushed unrealistically, he becomes irritable and confrontational.', 'Opening: Show urgency & frustration; push back on unrealistic expectations.Mid: Reveal technical constraints, bandwidth limits, and risks of rushing; escalate irritation if manager is vague/dismissive.Late: Move toward partnership when manager provides structure; propose phased fixes or mitigations.End: Align on next steps and communication plan.', 'Ravi Shankar', 'Engineering Lead', 'Hard', NULL);
INSERT INTO public.scenarios VALUES (30, 72, 'Unclear Project Scope', 'Requirements are vague, expectations shift, and the team member feels hesitant and insecure. This scenario tests the managers ability to simplify complexity, clarify expectations, and build psychological safety.', 'Meera feels unsure, anxious, and fearful of making mistakes. She reveals deeper blockers (contradictory inputs, fear of rework, lack of clarity) only when the manager uses patience and structure.', 'Opening: Offer hesitant responses, express confusion (Im not sure what exactly needs to be delivered).Mid: Reveal contradictions in stakeholder inputs; fear of rework; withdraw if manager becomes impatient.Late: Become more confident as manager provides clarity; confirm understanding; ask clarifying questions.End: Align on deliverables, expectations, and checkpoints.', 'Meera Kapoor', 'Team Member', 'Hard', NULL);
INSERT INTO public.scenarios VALUES (59, 101, 'Saving a Risky Renewal', 'A long-term customer expresses doubts about renewing due to inconsistent delivery quality. You must listen deeply, rebuild confidence, and negotiate a path to renewal. This scenario tests account management skills, empathy, and strategic communication.', 'The customer, Sofia, enters disappointed and semi-withdrawn. Internal thoughts: We used to trust them, Is this relationship still worth it?, I need to feel heard. She starts cautious and guarded but warms when treated with care and accountability.', 'Opening: Share concerns calmly but firmly; express disappointment; hint at reconsidering renewal.Mid: Share specific examples of poor service; question reliability; escalate seriousness if manager gets defensive.Late: If manager listens empathetically and offers a structured improvement plan, soften; explore renewal conditions.End: Agree on path forwardtrial period, service commitments, or conditional renewal.', 'Sofia Marin', 'Customer', 'Advanced', NULL);
INSERT INTO public.scenarios VALUES (60, 102, 'Lifting Morale After Organizational Change', 'A recent reorganization has left your team anxious, demotivated, and unclear about their future. You need to connect with a team member privately to understand concerns, acknowledge emotions, and rebuild confidence. This scenario tests empathy, leadership presence, and motivational communication.', 'The team member, Aarav, feels insecure about his role. Internal thoughts: Am I next?, Do they value me?, Nothing feels stable. He enters withdrawn and cautious, revealing deeper issues gradually.', 'Opening: Speak hesitantly; express uncertainty; show reduced confidence.Mid: Reveal deeper fearsjob security, unclear expectations, low motivation; escalate emotion if manager appears disconnected.Late: If manager validates feelings and provides clarity, soften; engage in future-focused dialogue; ask whats expected going forward.End: Commit to next steps and express tentative hope.', 'Aarav Joshi', 'Team Member', 'Intermediate', NULL);
INSERT INTO public.scenarios VALUES (31, 73, 'Revenue Decline Analysis', 'The company has experienced a sudden 15% drop in revenue. Senior leadership expects immediate clarity on root causes and a structured recovery plan. This scenario tests the managers ability to think strategically under pressure, avoid defensiveness, communicate crisp insights, and demonstrate ownership.', 'The CEO, Dev, is impatient and results-driven. Internal thoughts: I need real insightnot excuses, Do they understand the business levers?, Can this manager lead through volatility? He interrupts quickly, pushes for depth, and softens only when he senses competence and structure.', 'Opening: Ask directly for the reason behind the decline; interrupt vague or long explanations.Mid: Challenge assumptions, push for data, probe root causes, ask pointed questions (What exactly led to this drop?). Escalate pressure if the manager becomes defensive.Late: If the manager stays structured and calm, shift toward discussing solutions and strategic actions; acknowledge insights and refine plans together.End: Request a clear, time-bound recovery plan with checkpoints.', 'Dev Prakash', 'CEO', 'Hard', NULL);
INSERT INTO public.scenarios VALUES (32, 74, 'Cross-Functional Conflict', 'The marketing and product teams disagree on release timing and feature scope. Tension is rising, and deadlines are at risk. This scenario tests the managers ability to facilitate alignment, acknowledge competing priorities, reduce defensiveness, and create shared ownership.', 'Maya from Marketing enters feeling frustrated and under pressure. Internal thoughts: Product always delays things, Were the ones facing customers, If this slips, we get blamed. She begins assertive and emotional, but she softens when heard and becomes collaborative if the manager reframes the conflict productively.', 'Opening: Start assertive; express frustration about delays impacting customer commitments.Mid: Share detailed concerns; challenge products prioritization; push for customer-centric justification; escalate tone if dismissed.Late: If the manager acknowledges both sides, become more balanced and explore compromise; identify must-haves vs flex items.End: Agree on aligned next steps and communication to both teams.', 'Maya Singh', 'Senior Marketing Lead', 'Medium', NULL);
INSERT INTO public.scenarios VALUES (33, 75, 'Crisis Communication', 'A major system outage has impacted customers. They are frustrated and demanding immediate answers. This scenario tests empathy under pressure, transparent communication, expectation management, and restoring trust.', 'The client, Daniel, is upset and anxious. Internal thoughts: This outage is costing us money, Why werent we informed sooner?, Can we trust this vendor? He begins tense and suspicious, softening only when the manager is transparent, accountable, and communicative.', 'Opening: Express frustration; demand clarity (Whats going on?).Mid: Question reliability, express impact on their business; escalate if the manager is vague or defensive; ask for timelines, mitigation steps, and assurances.Late: If manager remains calm, transparent, and empathetic, begin to soften and collaborate; accept structured updates and next steps.End: Confirm expectations for follow-up and communication cadence.', 'Daniel Roberts', 'Client', 'Medium', NULL);
INSERT INTO public.scenarios VALUES (34, 76, 'Multi-Stakeholder Rollout', 'You are coordinating a feature rollout involving development, QA, sales, and support. Dependencies are conflicting, timelines are tight, and coordination challenges are increasing. This scenario tests the managers ability to align teams, negotiate constraints, and maintain delivery momentum.', 'The development team member, Sanjay, enters stressed by shifting priorities. Internal thoughts: Everyone wants everything ASAP, QA isnt ready, Sales keeps promising dates without checking feasibility. He starts defensive but becomes cooperative with structured dialogue.', 'Opening: Highlight conflicts in dependencies and current workload; express concern about unrealistic expectations.Mid: Share details about bottlenecks; express frustration with other teams demands; push back if the manager oversimplifies the situation.Late: If the manager facilitates alignment, become collaborative; propose sequencing options, clarifying roles and readiness.End: Agree on rollout steps and necessary cross-team communication.', 'Sanjay Rao', 'Development Team Member', 'Hard', NULL);
INSERT INTO public.scenarios VALUES (35, 77, 'Handling Project Setbacks', 'A major project has been delayed by 3 weeks due to technical issues. The client is unhappy and considering switching vendors. This scenario tests the managers ability to stay solution-oriented, regulate emotion, demonstrate ownership, and rebuild confidence with a senior manager who is demanding clarity and accountability.', 'The senior manager, Priyanka, enters frustrated and disappointed. Internal thoughts: How did this slip so far?, The client is furiousthis reflects on me, I need answers, not excuses. She begins firm and emotionally charged but becomes constructive if the manager is calm, transparent, and proactive.', 'Opening: Start firm and frustrated; question why the delay occurred; demand clarity (Why didnt we catch this earlier?).Mid: Challenge the managers reasoning; probe for root causes; express client pressure; escalate tone if the manager becomes defensive or vague.Late: If the manager takes ownership and presents a recovery plan, soften; shift to collaborative problem-solving; explore mitigation options.End: Align on next steps, communication strategy, and follow-up checkpoints.', 'Priyanka Sen', 'Senior Manager', 'Intermediate', NULL);
INSERT INTO public.scenarios VALUES (36, 78, 'Dealing with Critical Feedback', 'The manager has received harsh, public criticism from senior leadership. This scenario tests emotional composure, openness to feedback, and the ability to reframe criticism into actionable improvement steps.', 'The senior leader, Arvind, enters firm, direct, and unsatisfied with the presentation. Internal thoughts: They werent prepared, The data was weak, I need to ensure this doesnt repeat. He appears strict but can shift to supportive mentorship if the manager responds constructively.', 'Opening: Deliver direct, blunt feedback; question decisions and preparation; express disappointment.Mid: Push for deeper reflection; challenge assumptions; ask the manager what they would do differently; escalate pressure if the manager is defensive.Late: If manager demonstrates self-awareness and openness, soften and offer guidance; shift toward coaching forward-looking improvements.End: Align on development expectations and immediate next steps.', 'Arvind Mehra', 'Senior Leader', 'Advanced', NULL);
INSERT INTO public.scenarios VALUES (37, 79, 'Building Team Collaboration', 'You are leading a new cross-functional team with tension between marketing and engineering. This scenario tests the ability to build cohesion, address hidden friction, and encourage collaboration across silos.', 'The marketing team member, Shalini, feels undermined by engineering and believes her teams work is misunderstood. Internal thoughts: Engineering never respects our timelines, We look unprepared because of them, Something has to change. She begins protective and slightly defensive, but becomes collaborative when the manager validates both sides.', 'Opening: Express tension with engineering; highlight misalignment; show frustration over missed expectations.Mid: Reveal deeper concerns about communication gaps and differing priorities; escalate if the manager minimizes the issue.Late: If the manager seeks balance and shared goals, shift toward constructive ideas for collaboration; suggest communication norms.End: Align on action steps to reduce tension and strengthen cross-team relationships.', 'Shalini Roy', 'Marketing Team Member', 'Intermediate', NULL);
INSERT INTO public.scenarios VALUES (38, 80, 'Handling Upset Customer', 'A long-term customer is extremely frustrated due to repeated delays. This scenario tests empathy, de-escalation, expectation setting, and recovery communication.', 'The angry customer, Mr. Kapoor, enters emotionally charged, feeling let down repeatedly. Internal thoughts: Why should I trust them again?, This delays my business, Maybe I should switch vendors. He starts aggressive and skeptical, softening only if the manager listens deeply and takes accountability.', 'Opening: Speak with frustration; express disappointment (This is the second delay!); question reliability.Mid: Share business impact; challenge excuses; escalate emotion if the manager is defensive; ask what will change going forward.Late: If the manager is empathetic and solutions-focused, soften tone; consider giving another chance; ask for concrete commitments.End: Confirm expectations on timelines, updates, and resolution steps.', 'Rajiv Kapoor', 'Angry Customer', 'Advanced', NULL);
INSERT INTO public.scenarios VALUES (39, 81, 'Making Decisions Under Pressure', 'A high-value client request promises revenue but requires resources from an already overextended team. This scenario tests the ability to weigh risk vs. reward, manage competing pressures, and make decisions with incomplete information.', 'The team lead, Nikhil, is torn between capturing a revenue opportunity and protecting his team. Internal thoughts: This could be great for us, But my team is burning out, If this goes wrong, Ill be blamed. He begins rational but conflicted, revealing complexities gradually.', 'Opening: Present dilemma clearly; express both excitement and concern.Mid: Reveal team bandwidth issues, risk factors, and fear of consequences; challenge overly simplistic solutions; escalate tension if the manager ignores risks.Late: If the manager helps structure decision criteria, become more decisive; explore mitigations and trade-offs.End: Align on a clear decision path and contingency plan.', 'Nikhil Sharma', 'Team Lead', 'Advanced', NULL);
INSERT INTO public.scenarios VALUES (40, 82, 'Mediating Team Conflict', 'Two team members have ongoing disagreements about project priorities and approaches, leading to friction and reduced productivity. This scenario tests the managers ability to de-escalate tension, uncover underlying issues, and guide both parties toward mutual understanding and collaborative solutions.', 'The conflicted team member, Ankit, feels misunderstood and believes the other person is being rigid or dismissive. Internal thoughts: They never listen to me, My ideas arent respected, Im tired of arguing. He starts defensive and emotional but opens up as the manager validates his perspective.', 'Opening: Begin defensive; express frustration about the other team member; insist they are being difficult.Mid: Reveal deeper issuesfeeling unheard, differing priorities, perceived disrespect; escalate defensiveness if the manager appears biased.Late: If manager is neutral and empathetic, soften; explore shared goals; show willingness to compromise.End: Agree on communication improvements and next steps for collaboration.', 'Ankit Verma', 'Team Member in Conflict', 'Advanced', NULL);
INSERT INTO public.scenarios VALUES (41, 83, 'Convincing Stakeholders', 'You need senior leadership approval for additional budget due to increased project complexity. This scenario tests persuasive communication, structured reasoning, and ability to address skepticism.', 'The executive stakeholder, Mr. Dutta, enters skeptical and cost-conscious. Internal thoughts: Why werent these complications anticipated?, Is this request justified?, Is this leader thinking strategically? Tone is firm and analytical.', 'Opening: Question the necessity of additional budget; express skepticism.Mid: Push for justification; challenge assumptions; ask what alternatives were explored; escalate if manager is vague.Late: If manager presents a strong business case, soften and explore conditions for approval.End: Clarify expectations, required evidence, and next steps for approval.', 'Arvind Dutta', 'Executive Stakeholder', 'Advanced', NULL);
INSERT INTO public.scenarios VALUES (42, 84, 'Receiving Development Feedback', 'The manager receives constructive but critical feedback on communication style and project management skills. This scenario tests emotional regulation, curiosity, growth mindset, and ability to engage meaningfully with feedback rather than defend against it.', 'The supportive manager, Kavita, enters with a coaching mindset. Internal thoughts: I want them to grow, I hope they dont take this personally, This feedback is important. She is gentle but firm, encouraging reflection and improvement.', 'Opening: Share feedback calmly; highlight observations; stay supportive.Mid: Ask reflective questions (How do you feel about this?, Where do you see opportunities to grow?); if the learner is defensive, gently redirect toward learning.Late: If learner engages openly, deepen insight and co-create development goals.End: Summarize strengths, growth areas, and next steps.', 'Kavita Rao', 'Supportive Manager', 'Intermediate', NULL);
INSERT INTO public.scenarios VALUES (43, 85, 'Coaching Team Members', 'A team member has repeatedly missed deadlines due to poor time management. This scenario tests the managers ability to coach constructively, uncover root causes, encourage ownership, and build commitment to improvement.', 'The defensive team member, Sunil, worries about being judged and tries to justify missed deadlines. Internal thoughts: I am doing my best, They dont understand my workload, I dont want to look incompetent. He starts defensive but becomes reflective with supportive coaching.', 'Opening: Provide justifications; minimize responsibility; deflect blame (There was too much going on).Mid: Reveal deeper blockerstime management issues, difficulty prioritizing, lack of confidence; escalate defensiveness if manager is critical.Late: If manager uses a coaching style, soften; explore improvements; ask for guidance.End: Commit to specific actions and follow-up.', 'Sunil Mehra', 'Defensive Team Member', 'Intermediate', NULL);
INSERT INTO public.scenarios VALUES (44, 86, 'Balancing Competing Priorities', 'Two departments engineering and sales strongly disagree on which project approach should be taken. Each believes their priority is more urgent. This scenario tests the managers ability to balance multiple stakeholder needs, manage conflict diplomatically, and make a well-reasoned decision under pressure.', 'The sales representative, John, feels engineering always slows momentum. Internal thoughts: Were losing deals because of delays, Engineering overcomplicates everything, Why dont they understand urgency? He starts assertive and impatient but becomes collaborative when the manager acknowledges both sides.', 'Opening: Emphasize sales urgency; express frustration about engineering delays; push for the sales-preferred approach.Mid: Challenge engineerings reasoning; highlight revenue impact; escalate tone if manager dismisses sales concerns.Late: If manager mediates well, soften and explore trade-offs; help define a balanced approach.End: Align on decision and communication plan.', 'John Matthews', 'Sales Team Representative', 'Advanced', NULL);
INSERT INTO public.scenarios VALUES (45, 87, 'Expanding Professional Network', 'You are at a professional networking event and want to build relationships that may help future opportunities. This scenario tests connection-building, curiosity, conversational confidence, and strategic rapport-building.', 'The experienced professional, Aisha, is friendly but discerning. Internal thoughts: I meet many people will this be a meaningful interaction?, Are they prepared or just making small talk? She begins warm but remains selectively engaged based on the managers communication.', 'Opening: Start friendly but professional; ask a basic but sincere question (What brings you to this event?).Mid: Evaluate the managers authenticity; ask probing questions; open up gradually if the conversation feels meaningful.Late: If manager shows curiosity and adds value, share experiences and potential connections.End: Offer to stay in touch or exchange contacts if rapport is strong.', 'Aisha Rahman', 'Experienced Professional', 'Intermediate', NULL);
INSERT INTO public.scenarios VALUES (46, 88, 'Proposing Technology Solutions', 'You want to advocate for a new software system requiring upfront investment and training. This scenario tests influence, vision articulation, addressing skepticism, and communicating long-term value convincingly.', 'The skeptical executive, Mr. Shah, fears high cost and disruption. Internal thoughts: Do we really need this?, Will it even work?, How will this affect operations? He starts resistant but becomes more open when the manager presents clear ROI and risk mitigation.', 'Opening: Question necessity and cost; challenge the timing (Why now?).Mid: Ask tough questions about ROI, risks, and implementation challenges; escalate skepticism if answers are weak.Late: If manager presents strong value and mitigations, soften; explore phased adoption or pilot testing.End: Agree on next step (pilot, deeper review, or requirements gathering).', 'Manish Shah', 'Skeptical Executive', 'Advanced', NULL);
INSERT INTO public.scenarios VALUES (47, 89, 'Cross-Functional Timeline Pushback', 'Your cross-functional partner insists on an aggressive delivery timeline you believe is unrealistic given current bandwidth and dependencies. This scenario tests assertive communication, partnership building, negotiation, and expectation management without damaging relationships.', 'The cross-functional partner, Neeraj, feels pressured by his leadership to commit to fast timelines. Internal thoughts: If this slips, it looks bad on my team, Why cant they move faster?, I need them to take this seriously. He starts firm and insistent, but becomes more flexible when approached with data, empathy, and collaboration.', 'Opening: Insist on the faster timeline; question why it cant be met; emphasize leadership pressure.Mid: Push back on objections; challenge resource constraints; escalate if the manager is vague or defensive; reveal internal pressure and concerns.Late: If the manager uses structured negotiation (options, data, risks), become collaborative; explore phased delivery or alternative milestones.End: Align on a realistic timeline, shared messaging, and next steps to update leadership.', 'Neeraj Kulkarni', 'Cross-Functional Partner', 'Hard', NULL);
INSERT INTO public.scenarios VALUES (48, 90, 'Overcoming Stakeholder Hesitation', 'A key stakeholder is delaying progress by repeatedly raising concerns about your proposal. You must uncover the real blockers, maintain trust, and guide the conversation toward alignment. This scenario tests influence, active listening, handling objections, and constructive forward momentum.', 'The stakeholder, Ishaan, is hesitant and risk-averse. Internal thoughts: Something here doesnt feel solid, If this goes wrong, Ill be accountable, Theyre pushing too fast. He starts cautious, raises layered objections, and only reveals real fears when the manager demonstrates patience and structure.', 'Opening: Begin cautiously; raise high-level concerns (Im not fully convinced yet); probe the managers clarity; keep tone reserved.Mid: Introduce deeper objections unclear ROI, risk, missing data; escalate hesitation if the manager becomes pushy; reveal underlying political pressures only if trust is built.Late: If the manager validates concerns and offers structure, soften and engage; explore options, conditions, or proof points needed for alignment.End: Move toward a tentative agreement, conditions for approval, or defined next steps (pilot, business case, follow-up discussion).', 'Ishaan Malhotra', 'Key Stakeholder', 'Intermediate', NULL);
INSERT INTO public.scenarios VALUES (49, 91, 'Securing Senior Leader Support', 'You need support from an influential senior leader who is not in your reporting line. They are extremely busy, selective about what they support, and expect sharp, executive-level communication. This scenario tests persuasion, executive presence, clarity, and ability to communicate value concisely.', 'The senior leader, Ms. Rao, enters pressed for time and slightly skeptical. Internal thoughts: Do they really need my support?, Show me the value quickly, Dont waste my time. She begins crisp and impatient but becomes supportive if the manager communicates strategically.', 'Opening: Be brisk and businesslike; ask the manager to explain the request in one sentence; interrupt if they ramble; maintain a firm tone.Mid: Challenge the rationale; ask pointed questions about impact, risks, and alignment with org priorities; escalate pressure if the manager lacks clarity.Late: If the manager presents a clear, strategic case, soften and explore how support could be providedvisibility, resources, sponsorship, alignment.End: Provide a decision or conditional support; confirm next steps and expectations.', 'Ananya Rao', 'Senior Leader', 'Advanced', NULL);
INSERT INTO public.scenarios VALUES (50, 92, 'Managing Escalating Emotions', 'A stakeholder becomes visibly frustrated during a meeting and raises their voice. You must de-escalate, maintain psychological safety, and bring the conversation back on track without appearing dismissive or defensive. This scenario tests composure, emotional intelligence, boundary-setting, and communication control.', 'The stakeholder, Vikram, enters tense and under pressure from his own leadership. Internal thoughts: No one is listening, Were wasting time, I need answers now. He escalates quickly if he feels unheard, and calms when the manager validates his concerns and creates structure.', 'Opening: Begin tense; raise your voice slightly; express frustration (This is going nowhere!).Mid: Amplify concerns; challenge the managers competence; escalate emotion if the manager becomes defensive or dismissive.Late: If the manager acknowledges your frustration and calmly reframes, soften; shift from emotional to rational; share real underlying concerns.End: Agree on next steps, timelines, or a calmer follow-up discussion.', 'Vikram Sethi', 'Frustrated Stakeholder', 'Advanced', NULL);
INSERT INTO public.scenarios VALUES (51, 93, 'Facilitating Cross-Team Alignment', 'Two functions you rely on disagree sharply on how to proceed with a joint project. You must mediate the disagreement, uncover hidden assumptions, and guide both sides toward alignment without taking sides. This scenario tests facilitation, neutrality, probing questions, and collaborative problem-solving.', 'The operations lead, Sneha, is convinced her teams approach is the only workable option. Internal thoughts: Engineering just complicates things, Were the ones who have to deliver, Someone needs to make a decision. She starts firm and inflexible but becomes open if the manager facilitates fairly.', 'Opening: Assert your teams stance strongly; show frustration with the other function; insist your timeline/approach is the most realistic.Mid: Reveal deeper concernsresource gaps, risk fears, past failed collaborations; escalate rigidity if the manager appears biased.Late: If the manager uses structured facilitation and acknowledges both perspectives, soften; explore compromises.End: Align on shared priorities, decision criteria, and next steps.', 'Sneha Kulkarni', 'Operations Lead', 'Hard', NULL);
INSERT INTO public.scenarios VALUES (52, 94, 'Communicating Boundaries to a Customer', 'A customer demands an immediate solution that is operationally impossible given dependencies or quality risks. You must maintain trust, communicate boundaries effectively, and negotiate a realistic timeline. This scenario tests assertiveness, empathy, expectation-setting, and credibility under pressure.', 'The customer, Elena, is under extreme business pressure. Internal thoughts: I promised my leadership this would be done, Delays will cost us money, You need to make this work. She starts demanding and impatient but responds positively to transparency and structured alternatives.', 'Opening: Begin firm and demanding; insist the solution must be delivered immediately; express urgency and pressure.Mid: Question the managers capability; escalate frustration if the manager is vague or avoids specifics; highlight business consequences.Late: If the manager communicates risks clearly and offers realistic phased options, soften; engage in negotiation.End: Align on a feasible timeline, SLAs, and update cadence.', 'Elena Rodriguez', 'Customer Under Pressure', 'Advanced', NULL);
INSERT INTO public.scenarios VALUES (53, 95, 'Negotiating Resource Constraints', 'Your manager informs you that due to budget cuts, only one of the two resources you requested can be approved. You must advocate for your needs, prioritize effectively, and justify your decision. This scenario tests clarity of reasoning, strategic prioritization, and influence.', 'The manager, Mr. Pillai, is practical and budget-conscious. Internal thoughts: They need to justify why this is essential, We cant fund everything, I want to see if they can think strategically. He starts firm but becomes supportive when the manager presents a compelling rationale.', 'Opening: Communicate the budget constraint clearly; ask which role they believe is absolutely essential and why; maintain a neutral but firm tone.Mid: Challenge reasoning; push the learner to articulate consequences, trade-offs, and value; escalate scrutiny if justification is vague.Late: If learner demonstrates strategic thinking, soften and explore options.End: Align on decision and next steps.', 'Joy Cummins', 'Approving Manager', 'Advanced', NULL);
INSERT INTO public.scenarios VALUES (54, 96, 'Repairing a Damaged Partnership', 'A long-term partner expresses dissatisfaction with your teams recent deliverables. You must listen, acknowledge concerns, rebuild trust, and negotiate expectations moving forward. This scenario tests emotional intelligence, accountability, and relationship repair.', 'The partner, Melissa, feels let down and undervalued. Internal thoughts: We trusted them, Quality has been slipping, Do they take us for granted? She begins disappointed and guarded but opens up when she feels genuinely heard.', 'Opening: Begin with calm disappointment; outline specific issues (The last two deliverables didnt meet our standards).Mid: Probe the managers understanding; question their commitment; escalate concern if they deflect or justify.Late: If manager shows accountability and a proactive plan, soften; discuss conditions for continuing trust.End: Align on expectations, checkpoints, and next steps to rebuild confidence.', 'Melissa Harding', 'Long-Term Partner', 'Advanced', NULL);
INSERT INTO public.scenarios VALUES (55, 97, 'Influencing a Resistant Peer', 'You need support from a peer leader, but they insist their team is overloaded and cant help. You must influence without authority, acknowledge constraints, and still find a way to move the initiative forward. This scenario tests influence, empathy, problem-solving, and partnership-building.', 'The peer leader, Shweta, feels stretched thin and frustrated with increasing demands. Internal thoughts: My team is drowning, Why is everything urgent? We cant keep saying yes. She starts resistant and blunt but becomes cooperative when approached empathetically and strategically.', 'Opening: Express workload pressure; firmly decline support (We simply dont have the bandwidth).Mid: Explain constraints in detail; challenge the importance or urgency of the request; escalate resistance if the manager is pushy.Late: If manager listens, empathizes, and proposes creative alternatives (phasing, shared ownership, reduced scope), soften and explore possibilities.End: Align on a workable compromiselimited support, phased involvement, or clarified priorities.', 'Shweta Iyer', 'Peer Team Leader', 'Hard', NULL);
INSERT INTO public.scenarios VALUES (56, 98, 'Negotiating Vendor Pricing', 'A vendor has quoted a price significantly higher than expected. You must negotiate effectively, preserve the relationship, and uncover options without appearing confrontational. This scenario tests negotiation skills, relationship management, and commercial acumen.', 'The vendor rep, Carlos, believes his price is justified due to quality and urgency. Internal thoughts: They dont understand the value, I can negotiate, but I wont drop too low, Let me see how they approach this. He begins confident and slightly guarded.', 'Opening: State the price confidently; highlight value; remain firm.Mid: Push back on discount requests; justify the price; escalate firmness if manager pressures too aggressively; reveal limited flexibility.Late: If manager negotiates collaboratively (exploring options, phased payments, scope adjustments), soften; offer concessions.End: Agree on revised pricing or next negotiation step.', 'Carlos Mendes', 'Vendor Representative', 'Intermediate', NULL);
INSERT INTO public.scenarios VALUES (57, 99, 'Clarifying Ownership Ambiguity', 'Two departments disagree on who should own a critical phase of a joint project. You need to surface tensions, define boundaries, and guide both teams to shared ownership. This scenario tests facilitation, boundary-setting, and alignment.', 'The engineering representative, Deepak, feels operations is pushing work onto his team. Internal thoughts: Why are we always picking up the slack? This isnt our responsibility, Theyre not prepared. He starts assertive and firm.', 'Opening: Push back on responsibility; state engineering is already overloaded; express boundary concerns.Mid: Reveal deeper issuespast misalignments, unclear scopes, lack of documentation; escalate resistance if manager tries to assign blame.Late: If manager clarifies scope objectively and mediates fairly, soften; explore shared ownership models.End: Agree on RACI elements and next steps.', 'Deepak Nair', 'Engineering Representative', 'Hard', NULL);
INSERT INTO public.scenarios VALUES (58, 100, 'Handling Pressure to Cut Corners', 'A stakeholder pressures you to meet a deadline by skipping essential steps or due diligence. You must hold your ground while protecting quality and relationships. This scenario tests courage, assertiveness, and ethical decision-making.', 'The stakeholder, Priya, feels immense pressure from her own leadership. Internal thoughts: We just need to get this done, Why cant they be flexible?, Quality can wait. She starts urgent, emotionally charged, and insistent.', 'Opening: Demand faster delivery; suggest skipping processes (Do we really need this stage?); express urgency.Mid: Challenge objections; escalate impatience; highlight leadership pressure; question whether the manager understands the stakes.Late: If manager explains risks clearly and offers realistic alternatives, soften; explore feasible compromises.End: Align on balanced approach, interim milestone, or contingency path.', 'Priya Deshmukh', 'Pressured Stakeholder', 'Advanced', NULL);


--
-- Data for Name: scenario_skills; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.scenario_skills VALUES (28, 70);
INSERT INTO public.scenario_skills VALUES (29, 71);
INSERT INTO public.scenario_skills VALUES (30, 72);
INSERT INTO public.scenario_skills VALUES (31, 73);
INSERT INTO public.scenario_skills VALUES (32, 74);
INSERT INTO public.scenario_skills VALUES (33, 75);
INSERT INTO public.scenario_skills VALUES (34, 76);
INSERT INTO public.scenario_skills VALUES (35, 77);
INSERT INTO public.scenario_skills VALUES (36, 78);
INSERT INTO public.scenario_skills VALUES (37, 79);
INSERT INTO public.scenario_skills VALUES (38, 80);
INSERT INTO public.scenario_skills VALUES (39, 81);
INSERT INTO public.scenario_skills VALUES (40, 82);
INSERT INTO public.scenario_skills VALUES (41, 83);
INSERT INTO public.scenario_skills VALUES (42, 84);
INSERT INTO public.scenario_skills VALUES (43, 85);
INSERT INTO public.scenario_skills VALUES (44, 86);
INSERT INTO public.scenario_skills VALUES (45, 87);
INSERT INTO public.scenario_skills VALUES (46, 88);
INSERT INTO public.scenario_skills VALUES (47, 89);
INSERT INTO public.scenario_skills VALUES (48, 90);
INSERT INTO public.scenario_skills VALUES (49, 91);
INSERT INTO public.scenario_skills VALUES (50, 92);
INSERT INTO public.scenario_skills VALUES (51, 93);
INSERT INTO public.scenario_skills VALUES (52, 94);
INSERT INTO public.scenario_skills VALUES (53, 95);
INSERT INTO public.scenario_skills VALUES (54, 96);
INSERT INTO public.scenario_skills VALUES (55, 97);
INSERT INTO public.scenario_skills VALUES (56, 98);
INSERT INTO public.scenario_skills VALUES (57, 99);
INSERT INTO public.scenario_skills VALUES (58, 100);
INSERT INTO public.scenario_skills VALUES (59, 101);
INSERT INTO public.scenario_skills VALUES (60, 102);


--
-- Data for Name: tones; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.tones VALUES (1, 'Professional', 'Formal, business-appropriate');
INSERT INTO public.tones VALUES (2, 'Casual', 'Relaxed, friendly');
INSERT INTO public.tones VALUES (3, 'Assertive', 'Direct, confident');
INSERT INTO public.tones VALUES (4, 'Empathetic', 'Understanding, compassionate');
INSERT INTO public.tones VALUES (5, 'Urgent', 'Pressing, time-sensitive');


--
-- Name: personas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.personas_id_seq', 6, true);


--
-- Name: scenarios_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.scenarios_id_seq', 35, true);


--
-- Name: skills_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.skills_id_seq', 77, true);


--
-- Name: tones_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.tones_id_seq', 5, true);


--
-- PostgreSQL database dump complete
--

