-- Role Archetypes seed data (19 role types)
-- These define role types with skill dimensions and interview patterns

INSERT INTO role_archetypes (id, name, description, primary_skill_dimensions, common_interview_types, typical_task_types, common_failure_modes, role_category)
VALUES
('core_software_engineer', 'Core Software Engineer', 'General software engineering roles: backend/frontend/fullstack/mobile. Focus on coding, problem solving, debugging, and system thinking.', 
  '["problem_solving", "coding_fluency", "debugging", "system_thinking", "communication", "tradeoffs"]'::jsonb,
  '["technical", "coding", "hiring_manager", "behavioral"]'::jsonb,
  '["coding", "debugging", "code_modification", "code_review", "system_design_light"]'::jsonb,
  '["vague reasoning", "misses edge cases", "incorrect complexity", "cannot explain decisions", "weak debugging approach"]'::jsonb,
  'tech'),

('data_analyst', 'Data Analyst', 'Analytics roles focused on SQL, metrics, dashboards, and insight storytelling.',
  '["sql", "data_cleaning", "metrics", "analysis_storytelling", "business_context", "communication"]'::jsonb,
  '["sql", "analytics", "hiring_manager", "behavioral"]'::jsonb,
  '["sql_case", "analytics_case", "data_interpretation", "presentation_summary"]'::jsonb,
  '["unclear metric definitions", "weak SQL joins/window functions", "jumps to conclusions", "no validation/QA", "weak business framing"]'::jsonb,
  'data'),

('data_engineer', 'Data Engineer', 'Pipelines, ETL/ELT, warehousing, reliability, and performance.',
  '["sql", "etl_pipelines", "data_modeling", "reliability", "performance", "debugging"]'::jsonb,
  '["technical", "sql", "coding", "hiring_manager", "behavioral"]'::jsonb,
  '["sql_case", "debug_pipeline", "design_data_model", "coding_light"]'::jsonb,
  '["poor data modeling", "ignores data quality", "weak tradeoffs", "no monitoring/alerting", "unclear ownership"]'::jsonb,
  'data'),

('data_scientist', 'Data Scientist', 'Experimentation, modeling basics, product analytics, and reasoning.',
  '["stats", "experimentation", "modeling_basics", "analysis", "business_context", "communication"]'::jsonb,
  '["technical", "ml", "coding", "hiring_manager", "behavioral"]'::jsonb,
  '["stats_case", "product_sense_case", "modeling_explain", "analysis_storytelling"]'::jsonb,
  '["confuses causation", "weak experiment design", "math gaps", "overfits explanation", "no tradeoffs/assumptions"]'::jsonb,
  'data'),

('ml_engineer', 'Machine Learning Engineer', 'Applied ML in production: training, serving, evaluation, and MLOps.',
  '["ml_fundamentals", "model_evaluation", "mlops", "system_thinking", "debugging", "communication"]'::jsonb,
  '["technical", "ml", "coding", "hiring_manager", "behavioral"]'::jsonb,
  '["ml_case", "design_ml_system", "debug_model", "coding_medium"]'::jsonb,
  '["cannot explain evaluation", "weak data leakage awareness", "no monitoring", "hand-wavy features", "poor tradeoffs"]'::jsonb,
  'data'),

('infra_platform', 'Infrastructure / Platform Engineer', 'DevOps/SRE/platform engineering: reliability, automation, and systems.',
  '["linux", "networking", "reliability", "automation", "incident_response", "communication"]'::jsonb,
  '["technical", "coding", "hiring_manager", "behavioral"]'::jsonb,
  '["incident_simulation", "design_reliability", "debug_infra", "coding_light"]'::jsonb,
  '["no runbook thinking", "weak root cause", "ignores observability", "poor prioritization", "unsafe changes"]'::jsonb,
  'tech'),

('security_engineer', 'Security Engineer', 'Security engineering across appsec/cloud/security operations depending on role.',
  '["security_fundamentals", "threat_modeling", "risk_assessment", "incident_response", "communication", "tooling"]'::jsonb,
  '["technical", "coding", "hiring_manager", "behavioral"]'::jsonb,
  '["threat_model_case", "incident_simulation", "policy_review", "tooling_questions"]'::jsonb,
  '["tactical without risk reasoning", "weak threat models", "misses basics", "poor communication", "no triage/prioritization"]'::jsonb,
  'tech'),

('qa_test_engineer', 'QA / Test Engineer', 'Quality engineering: test strategy, automation, and defect triage.',
  '["test_strategy", "automation", "debugging", "communication", "risk_based_testing", "collaboration"]'::jsonb,
  '["technical", "coding", "hiring_manager", "behavioral"]'::jsonb,
  '["test_plan_case", "bug_triage", "automation_design", "code_review_light"]'::jsonb,
  '["tests are shallow", "no edge cases", "poor prioritization", "unclear reproduction steps", "weak collaboration signals"]'::jsonb,
  'tech'),

('product_manager', 'Product Manager', 'Product discovery, prioritization, execution, stakeholder management, and product sense.',
  '["product_sense", "prioritization", "customer_empathy", "execution", "stakeholder_management", "communication"]'::jsonb,
  '["product", "hiring_manager", "behavioral", "case"]'::jsonb,
  '["product_case", "strategy_case", "metrics_case", "execution_scenario", "presentation_summary"]'::jsonb,
  '["solution jumps", "unclear success metrics", "weak tradeoffs", "poor stakeholder handling", "no customer insight"]'::jsonb,
  'product'),

('technical_program_manager', 'Technical Program Manager', 'Cross-functional delivery of complex technical programs with risk and dependency management.',
  '["program_management", "technical_depth", "risk_management", "stakeholder_management", "execution", "communication"]'::jsonb,
  '["hiring_manager", "behavioral", "technical"]'::jsonb,
  '["program_case", "risk_dependency_case", "technical_depth_probe", "execution_scenario"]'::jsonb,
  '["no critical path", "weak risk plans", "unclear ownership", "poor cross-team alignment", "hand-wavy technicals"]'::jsonb,
  'product'),

('product_designer', 'Product Designer', 'End-to-end product design: problem framing, interaction design, UI craft, and collaboration.',
  '["problem_framing", "user_empathy", "interaction_design", "visual_design", "iteration", "communication"]'::jsonb,
  '["portfolio", "hiring_manager", "behavioral", "case"]'::jsonb,
  '["portfolio_walkthrough", "design_case", "critique", "handoff_scenario"]'::jsonb,
  '["unclear rationale", "design for self not user", "no iteration", "weak tradeoffs", "poor collaboration signals"]'::jsonb,
  'product'),

('marketing_growth', 'Marketing / Growth', 'Marketing and growth: funnel thinking, messaging, experiments, and analytics.',
  '["positioning", "messaging", "funnel_metrics", "experimentation", "channel_strategy", "communication"]'::jsonb,
  '["hiring_manager", "behavioral", "case"]'::jsonb,
  '["growth_case", "campaign_case", "analytics_case", "presentation_summary"]'::jsonb,
  '["vanity metrics focus", "weak hypothesis", "no measurement plan", "unclear audience", "poor prioritization"]'::jsonb,
  'business'),

('sales_account', 'Sales / Account', 'Sales roles: discovery, objection handling, negotiation, and pipeline discipline.',
  '["discovery", "objection_handling", "communication", "negotiation", "process_discipline", "customer_empathy"]'::jsonb,
  '["sales_roleplay", "hiring_manager", "behavioral"]'::jsonb,
  '["roleplay_discovery", "objection_roleplay", "case_account_plan", "presentation_pitch"]'::jsonb,
  '["talks too much", "no questions", "pushy not consultative", "weak follow-up", "no process discipline"]'::jsonb,
  'sales'),

('customer_success', 'Customer Success', 'CSM roles: onboarding, adoption, renewals, escalations, and value realization.',
  '["relationship_management", "problem_solving", "communication", "value_realization", "process", "stakeholder_management"]'::jsonb,
  '["hiring_manager", "behavioral", "case"]'::jsonb,
  '["onboarding_case", "renewal_risk_case", "escalation_roleplay", "qbr_presentation"]'::jsonb,
  '["reactive only", "no success plan", "weak escalation handling", "unclear value metrics", "poor stakeholder mapping"]'::jsonb,
  'sales'),

('bizops_strategy', 'BizOps / Strategy', 'BizOps/strategy: structured problem solving, analysis, and stakeholder alignment.',
  '["structured_thinking", "analysis", "business_context", "stakeholder_management", "communication", "prioritization"]'::jsonb,
  '["case", "hiring_manager", "behavioral"]'::jsonb,
  '["strategy_case", "ops_case", "metrics_case", "presentation_summary"]'::jsonb,
  '["unstructured approach", "weak assumptions", "no sensitivity analysis", "unclear recommendation", "poor stakeholder handling"]'::jsonb,
  'business'),

('operations_general', 'Operations', 'Operations: process improvement, execution coordination, and KPI ownership.',
  '["process_improvement", "execution", "prioritization", "data_literacy", "communication", "stakeholder_management"]'::jsonb,
  '["hiring_manager", "behavioral", "case"]'::jsonb,
  '["ops_case", "process_mapping", "incident_ops", "presentation_summary"]'::jsonb,
  '["no measurable KPIs", "weak root cause", "poor prioritization", "unclear ownership", "reactive"]'::jsonb,
  'business'),

('finance_strategy', 'Finance & Strategy', 'Finance/FP&A/strategy: modeling, business judgment, and narrative.',
  '["financial_modeling", "business_judgment", "analysis", "communication", "stakeholder_management", "risk_awareness"]'::jsonb,
  '["technical", "hiring_manager", "behavioral", "case"]'::jsonb,
  '["modeling_case", "variance_analysis", "strategy_case", "presentation_summary"]'::jsonb,
  '["math errors", "no assumptions", "weak business linkage", "unclear narrative", "misses risks"]'::jsonb,
  'business'),

('consulting_general', 'Consulting', 'Management consulting: case interviews, structured problem solving, and synthesis.',
  '["structured_thinking", "hypothesis_driven", "quantitative_reasoning", "communication", "business_context", "synthesis"]'::jsonb,
  '["case", "behavioral", "panel"]'::jsonb,
  '["case_interview", "market_sizing", "exhibit_analysis", "final_reco_presentation"]'::jsonb,
  '["unstructured", "no hypotheses", "poor math", "weak synthesis", "rambling communication"]'::jsonb,
  'business')

ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  primary_skill_dimensions = EXCLUDED.primary_skill_dimensions,
  common_interview_types = EXCLUDED.common_interview_types,
  typical_task_types = EXCLUDED.typical_task_types,
  common_failure_modes = EXCLUDED.common_failure_modes,
  role_category = EXCLUDED.role_category,
  updated_at = NOW();
