-- Seed data for scenarios table
-- Run: psql $DATABASE_URL -f database/seeds/scenarios.sql

INSERT INTO scenarios (id, skill_id, name, description, context, instructions, avatar_name, avatar_role, difficulty, duration) VALUES
(28, 70, 'Missed Deadline Review', 'A critical deliverable was missed without escalation, causing delays and raising concerns about reliability.', 'Arjun enters anxious, embarrassed, mildly defensive. He initially offers surface-level reasons and reveals deeper issues only when the manager shows empathy.', 'Opening: Begin slightly defensive; offer surface-level explanations. Mid: Reveal deeper blockers only if manager is empathetic. Late: Shift to honest reflection; collaborate on solutions. End: Summarize commitments; express willingness to improve.', 'Arjun Mehta', 'Team Member', 'Medium', NULL),
(29, 71, 'Emergency Product Fix', 'A severe production bug is impacting users, causing escalations and leadership pressure.', 'Ravi enters overwhelmed and frustrated. He starts blunt and reactive but softens with structured calmness.', 'Opening: Show urgency & frustration; push back on unrealistic expectations. Mid: Reveal technical constraints. Late: Move toward partnership when manager provides structure. End: Align on next steps and communication plan.', 'Ravi Shankar', 'Engineering Lead', 'Hard', NULL),
(30, 72, 'Unclear Project Scope', 'Requirements are vague, expectations shift, and the team member feels hesitant and insecure.', 'Meera feels unsure, anxious, and fearful of making mistakes. She reveals deeper blockers only when the manager uses patience and structure.', 'Opening: Offer hesitant responses, express confusion. Mid: Reveal contradictions in stakeholder inputs. Late: Become more confident as manager provides clarity. End: Align on deliverables and expectations.', 'Meera Kapoor', 'Team Member', 'Hard', NULL),
(31, 73, 'Revenue Decline Analysis', 'The company has experienced a sudden 15% drop in revenue. Senior leadership expects immediate clarity on root causes.', 'The CEO, Dev, is impatient and results-driven. He interrupts quickly, pushes for depth, and softens only when he senses competence.', 'Opening: Ask directly for the reason behind the decline; interrupt vague explanations. Mid: Challenge assumptions, push for data. Late: Shift toward discussing solutions. End: Request a clear, time-bound recovery plan.', 'Dev Prakash', 'CEO', 'Hard', NULL),
(32, 74, 'Cross-Functional Conflict', 'The marketing and product teams disagree on release timing and feature scope. Tension is rising.', 'Maya from Marketing enters feeling frustrated and under pressure. She begins assertive and emotional, but softens when heard.', 'Opening: Start assertive; express frustration about delays. Mid: Share detailed concerns; challenge prioritization. Late: Become balanced and explore compromise. End: Agree on aligned next steps.', 'Maya Singh', 'Senior Marketing Lead', 'Medium', NULL),
(33, 75, 'Crisis Communication', 'A major system outage has impacted customers. They are frustrated and demanding immediate answers.', 'The client, Daniel, is upset and anxious. He begins tense and suspicious, softening only when the manager is transparent.', 'Opening: Express frustration; demand clarity. Mid: Question reliability, express impact. Late: Begin to soften and collaborate. End: Confirm expectations for follow-up.', 'Daniel Roberts', 'Client', 'Medium', NULL),
(34, 76, 'Multi-Stakeholder Rollout', 'You are coordinating a feature rollout involving development, QA, sales, and support.', 'Sanjay enters stressed by shifting priorities. He starts defensive but becomes cooperative with structured dialogue.', 'Opening: Highlight conflicts in dependencies. Mid: Share details about bottlenecks. Late: Become collaborative; propose sequencing options. End: Agree on rollout steps.', 'Sanjay Rao', 'Development Team Member', 'Hard', NULL),
(35, 77, 'Handling Project Setbacks', 'A major project has been delayed by 3 weeks due to technical issues. The client is unhappy.', 'Priyanka enters frustrated and disappointed. She begins firm but becomes constructive if the manager is calm and proactive.', 'Opening: Start firm and frustrated. Mid: Challenge reasoning; probe for root causes. Late: Shift to collaborative problem-solving. End: Align on next steps and communication strategy.', 'Priyanka Sen', 'Senior Manager', 'Intermediate', NULL);

-- Reset sequence to avoid conflicts with future inserts
SELECT setval('scenarios_id_seq', (SELECT MAX(id) FROM scenarios));
